siteTitle = "ebadfd explorations"
domain = "ebadfd.tech"

[defaultAuthor]
name = "z9fr"
handle = "z9fr"
jobTitle = "Software Engineer"
inSystem = true
sameAs = ["https://x.com/3badfd", "https://github.com/ebadfd"]
twitter = "3badfd"
github = "ebadfd"

[[notableProjects]]
url = "https://github.com/ebadfd/site"
title = "site"
description = "Personal blog"

[[contactLinks]]
url = "https://x.com/3badfd"
title = "X formerly twitter"
description = "X profile"

[[contactLinks]]
url = "https://github.com/ebadfd"
title = "GitHub"
description = "Github profile"
