siteTitle = "z9fr blog"
domain = "z9fr.xyz"

[defaultAuthor]
name = "z9fr"
handle = "z9fr"
jobTitle = "Software Engineer"
inSystem = true
sameAs = ["https://twitter.com/sigsegvme", "https://github.com/z9fr"]
twitter = "sigsegvme"
github = "z9fr"

[[notableProjects]]
url = "https://github.com/z9fr/site"
title = "site"
description = "Personal blog"

[[contactLinks]]
url = "https://twitter.com/sigsegvme"
title = "Twitter"
description = "Twitter profile"

[[contactLinks]]
url = "https://github.com/z9fr"
title = "GitHub"
description = "Github profile"
