# fly.toml app configuration file generated for z9fr-site on 2023-12-26T23:19:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "z9fr-site"
primary_region = "sin"

[build]

[env]
  PORT = "8080"
  RUST_LOG= "site=trace"

[metrics]
port = 8080
path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
